sudo: required

services:
  - docker

before_install:
  - docker build -t omran/docker-react -f Dockerfile.dev .
  - docker run omran/docker-react npm run test -- --coverage

scripts:
  - npm run test -- --coverage